server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
pingmall:
  jwt:
    #登录校验的密钥
    secret: pingmall@Login(Auth}*^30)&HeiMahaha%
    #公钥地址
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub
    #私钥地址
    priKeyPath: C:\\tmp\\rsa\\rsa.pri
    #过期时间（分钟）
    expire: 30
    cookieName: PM_TOKEN