server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.59.132
    username: pingmall
    password: cl910526
    virtual-host: /pingmall
pingmall:
  sms:
    #阿里云AccessKeyID
    accessKeyId: ########
    #阿里云AccessKeySecret
    accessKeySecret: ########
    #签名名称
    signName: 品茂商城
    #模板名称
    verifyCodeTemplate: ########
