server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  #RabbitMQ相关配置
  rabbitmq:
    #RabbitMQ主机地址
    host: 192.168.59.132
    #指定虚拟机主机地址
    virtual-host: /pingmall
    username: pingmall
    password: cl910526
    template:
      #指定交换机
      exchange: PINGMALL.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
    registry-fetch-interval-seconds: 10