server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.59.132
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
pingmall:
  jwt:
    #公钥地址
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub
    cookieName: PM_TOKEN